/*
 * File: app/store/ConsumptionModels.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.store.ConsumptionModels', {
	extend: 'Ext.data.Store',

	requires: [
		'C.model.ConsumptionModel'
	],

	constructor: function(cfg) {
		var me = this;
		cfg = cfg || {};
		me.callParent([Ext.apply({
			autoLoad: false,
			autoSync: true,
			storeId: 'MyJsonStore8',
			model: 'C.model.ConsumptionModel',
			clearOnPageLoad: false,
			remoteFilter: true,
			proxy: {
				type: 'rest',
				url: '/cassandra/api/consmod',
				reader: {
					type: 'json',
					root: 'data',
					totalProperty: 'size'
				},
				writer: {
					type: 'json'
				}
			},
			listeners: {
				datachanged: {
					fn: me.onJsonstoreDataChangeD,
					scope: me
				}
			}
		}, cfg)]);
	},

	onJsonstoreDataChangeD: function(abstractstore, options) {
		console.info('ConsumptionModel data changed.', abstractstore, options);
		var store = abstractstore;

	}

});