/*
 * File: app/store/PricingTypeStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.store.PricingTypeStore', {
	extend: 'Ext.data.Store',

	constructor: function(cfg) {
		var me = this;
		cfg = cfg || {};
		me.callParent([Ext.apply({
			autoLoad: false,
			storeId: 'MyStore8',
			data: [
				{
					pricingTypeName: 'Scalar Energy Pricing',
					pricingTypeTag: 'ScalarEnergyPricing'
				},
				{
					pricingTypeName: 'Scalar Energy Pricing Time Zones',
					pricingTypeTag: 'ScalarEnergyPricingTimeZones'
				},
				{
					pricingTypeName: 'Energy Power Pricing',
					pricingTypeTag: 'EnergyPowerPricing'
				},
				{
					pricingTypeName: 'All Inclusive Pricing',
					pricingTypeTag: 'AllInclusivePricing'
				},
				{
					pricingTypeName: 'TOU Pricing',
					pricingTypeTag: 'TOUPricing'
				}
			],
			fields: [
				{
					name: 'pricingTypeName',
					type: 'string'
				},
				{
					name: 'pricingTypeTag',
					type: 'string'
				}
			]
		}, cfg)]);
	}
});