/*
 * File: app/store/ResultsPieChartsStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.store.ResultsPieChartsStore', {
	extend: 'Ext.data.Store',

	constructor: function(cfg) {
		var me = this;
		cfg = cfg || {};
		me.callParent([Ext.apply({
			autoLoad: false,
			storeId: 'ResultsPieChartsStore',
			proxy: {
				type: 'ajax',
				limitParam: '',
				noCache: false,
				pageParam: '',
				startParam: '',
				url: '/cassandra/api/piecharts',
				reader: {
					type: 'json'
				}
			},
			listeners: {
				load: {
					fn: me.onJsonstoreLoad,
					scope: me
				}
			}
		}, cfg)]);
	},

	onJsonstoreLoad: function(store, records, successful, eOpts) {
		var rootData = store.proxy.reader.jsonData;

		if (rootData && rootData.data[0]) {
			if (rootData.data[0].activities) {
				Ext.getStore('ResultsActivityStore').loadData(rootData.data[0].activities);
			}
			if (rootData.data[0].appliances) {
				Ext.getStore('ResultsApplianceStore').loadData(rootData.data[0].appliances);
			}
		}
	}

});