/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
	enabled: true
});

Ext.application({
	models: [
		'Project',
		'Scenario',
		'Installation',
		'Person',
		'Activity',
		'ActivityModel',
		'Appliance',
		'ConsumptionModel',
		'SimulationParam',
		'Run',
		'Distribution',
		'DistributionParam',
		'ConsumptionModelParam'
	],
	stores: [
		'Projects',
		'Scenarios',
		'NavigationTreeStore',
		'Installations',
		'Persons',
		'Appliances',
		'Activities',
		'ActivityModels',
		'Distributions',
		'ConsumptionModels',
		'SimulationParams',
		'Runs',
		'DayTypeStore',
		'ActmodAppliances',
		'DistributionParams',
		'ConsumptionModelParams',
		'DistributionInActivity'
	],
	views: [
		'MyViewport',
		'ScenariosGrid',
		'InstallationsGrid',
		'PersonsGrid',
		'AppliancesGrid',
		'ActivitiesGrid',
		'DistributionsGrid',
		'ConsumptionModelsGrid',
		'SimulationParamsGrid',
		'RunsGrid',
		'ActivityModelsGrid',
		'ActivityModelsForm',
		'ContainsAppliancesGrid',
		'DistributionsForm',
		'DistributionParamsGrid',
		'ConsumptionModelParamsGrid',
		'ConsumptionModelsForm',
		'DistributionInActivityGrid'
	],
	autoCreateViewport: true,
	name: 'C'
});
