/*
 * File: app/model/ActivityModel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.model.ActivityModel', {
	extend: 'Ext.data.Model',

	idProperty: '_id',

	fields: [
		{
			name: '_id',
			persist: false
		},
		{
			name: 'name',
			type: 'string'
		},
		{
			name: 'type',
			type: 'string'
		},
		{
			name: 'description',
			type: 'string'
		},
		{
			name: 'shiftable',
			type: 'boolean'
		},
		{
			name: 'day_type',
			defaultValue: 'working',
			type: 'string'
		},
		{
			name: 'act_id'
		},
		{
			name: 'containsAppliances'
		},
		{
			name: 'duration'
		},
		{
			name: 'startTime'
		},
		{
			name: 'repeatsNrOfTime'
		},
		{
			name: 'distributions',
			mapping: 'distributions_counter',
			persist: false,
			type: 'int'
		}
	]
});