/*
 * File: app/model/Cluster.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.model.Cluster', {
	extend: 'Ext.data.Model',

	idProperty: 'name',

	fields: [
		{
			name: 'name',
			type: 'string'
		},
		{
			name: 'installations_',
			type: 'string'
		},
		{
			convert: function(v, rec) {
				Ext.each(v, function(inst_id) {
					Ext.Ajax.request({
						url: '/cassandra/api/inst/'+inst_id,
						method: 'GET',
						scope: this,
						success: function(response, opts) {
							var response_obj = Ext.JSON.decode(response.responseText);
							var inst_obj = response_obj.data[0];
							var inst_template = '<span class= "light_gey"> Id: </span>' + inst_obj._id + '</br>'+
							'<span class= "light_gey">Name: </span>' + inst_obj.name + '</br>'+
							'<span class= "light_gey">Description: </span>' + inst_obj.description + '</br>'+
							'<span class= "light_gey">Type: </span>' + inst_obj.type + '</br></br>';
							rec.set("installations_", rec.get("installations_") + inst_template);
						}
					});
				});
			},
			name: 'installations',
			type: 'string'
		},
		{
			name: 'pricing_id',
			type: 'string'
		},
		{
			name: 'base_prc_id',
			type: 'string'
		}
	]
});