/*
 * File: app/model/Csn.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.model.Csn', {
	extend: 'Ext.data.Model',

	idProperty: '_id',

	fields: [
		{
			name: '_id',
			persist: false
		},
		{
			defaultValue: 'InstallationType',
			name: 'graphType',
			type: 'string'
		},
		{
			name: 'prj_id'
		},
		{
			name: 'img_path',
			persist: false,
			type: 'string'
		},
		{
			name: 'run_id'
		},
		{
			defaultValue: '0',
			name: 'minWeight',
			type: 'float'
		},
		{
			name: 'noedges',
			type: 'boolean'
		}
	]
});