/*
 * File: app/model/Installation.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.model.Installation', {
	extend: 'Ext.data.Model',

	idProperty: '_id',

	fields: [
		{
			name: 'name',
			type: 'string'
		},
		{
			name: 'type',
			type: 'string'
		},
		{
			name: 'description',
			type: 'string'
		},
		{
			name: 'scenario_id'
		},
		{
			name: 'belongsToInstallation',
			useNull: false
		},
		{
			name: 'location',
			type: 'string'
		},
		{
			name: 'x',
			type: 'float'
		},
		{
			name: 'y',
			type: 'float'
		},
		{
			name: '_id'
		},
		{
			name: 'appliances',
			mapping: 'appliances_counter',
			persist: false,
			type: 'int'
		},
		{
			name: 'persons',
			mapping: 'persons_counter',
			persist: false,
			type: 'int'
		}
	]
});