/*
 * File: app/model/LightingModule.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.model.LightingModule', {
	extend: 'Ext.data.Model',

	fields: [
		{
			name: '_id',
			persist: false
		},
		{
			name: 'inst_id'
		},
		{
			name: 'luminaireHeight',
			type: 'float'
		},
		{
			name: 'workplaneHeight',
			type: 'float'
		},
		{
			name: 'ballastFactor',
			type: 'float'
		},
		{
			name: 'ballastLampPhotometerFactor',
			type: 'float'
		},
		{
			name: 'equipmentOperatingFactor',
			type: 'float'
		},
		{
			name: 'heatExtractionThermalFactor',
			type: 'float'
		},
		{
			name: 'lampPositionFactor',
			type: 'float'
		},
		{
			name: 'luminaireAmbientTemperatureFactor',
			type: 'float'
		},
		{
			name: 'luminaireSurfaceDepreciationFactor',
			type: 'float'
		},
		{
			name: 'voltageToLuminaireFactor',
			type: 'float'
		},
		{
			name: 'lampBurnoutFactor',
			type: 'float'
		},
		{
			name: 'lampLumenDepreciationFactor',
			type: 'float'
		},
		{
			name: 'luminaireDirtDepreciationFactor',
			type: 'float'
		},
		{
			name: 'roomSurfaceDirtDepreciationFactor',
			type: 'float'
		},
		{
			name: 'initialLumenOutput',
			type: 'float'
		},
		{
			name: 'numberOfLamps',
			type: 'int'
		},
		{
			name: 'numberOfLuminaires',
			type: 'int'
		},
		{
			name: 'ceilingReflectanceValue',
			type: 'float'
		},
		{
			name: 'wallsReflectanceValue',
			type: 'float'
		},
		{
			name: 'floorReflectanceValue',
			type: 'float'
		},
		{
			name: 'ceilingHeight',
			type: 'float'
		},
		{
			name: 'roomLength',
			type: 'float'
		},
		{
			name: 'roomWidth',
			type: 'float'
		},
		{
			name: 'visualComfort',
			type: 'float'
		},
		{
			name: 'backgroundLuminanceLevel',
			type: 'float'
		},
		{
			name: 'objectLuminanceLevel',
			type: 'float'
		},
		{
			name: 'steradian',
			type: 'float'
		},
		{
			name: 'solidAngle',
			type: 'float'
		},
		{
			name: 'positionIndex',
			type: 'float'
		},
		{
			name: 'minimumIlluminance',
			type: 'float'
		}
	]
});