/*
 * File: app/model/LightingModule.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.model.LightingModule', {
	extend: 'Ext.data.Model',

	fields: [
		{
			name: '_id'
		},
		{
			name: 'length',
			type: 'float'
		},
		{
			name: 'width',
			type: 'float'
		},
		{
			name: 'height',
			type: 'float'
		},
		{
			name: 'luminaires_no',
			type: 'int'
		},
		{
			name: 'lamps_no',
			type: 'int'
		},
		{
			name: 'initial_lamp_lumen',
			type: 'float'
		},
		{
			name: 'luminaire_height',
			type: 'float'
		},
		{
			name: 'workplane_height',
			type: 'float'
		},
		{
			name: 'ceilings',
			type: 'float'
		},
		{
			name: 'walls',
			type: 'float'
		},
		{
			name: 'floors',
			type: 'float'
		},
		{
			name: 'recoverable_llf',
			type: 'string'
		},
		{
			name: 'non_recoverable_llf',
			type: 'string'
		},
		{
			name: 'object_luminance_lvl',
			type: 'float'
		},
		{
			name: 'bg_luminance_lvl',
			type: 'float'
		},
		{
			name: 'bg_luminance_lvl',
			type: 'float'
		},
		{
			name: 'observed_illuminance',
			type: 'float'
		},
		{
			name: 'steradian',
			type: 'float'
		},
		{
			name: 'solid_angle',
			type: 'float'
		},
		{
			name: 'position_index',
			type: 'float'
		},
		{
			name: 'min_illuminance',
			type: 'float'
		}
	]
});