/*
 * File: app/model/Scenario.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.model.Scenario', {
	extend: 'Ext.data.Model',

	idProperty: '_id',

	fields: [
		{
			name: '_id',
			persist: false
		},
		{
			name: 'project_id'
		},
		{
			name: 'name',
			type: 'string'
		},
		{
			name: 'description',
			type: 'string'
		},
		{
			defaultValue: 'static',
			name: 'setup',
			type: 'string'
		},
		{
			defaultValue: true,
			name: 'editable',
			type: 'boolean'
		},
		{
			mapping: 'installations_counter',
			name: 'installations',
			persist: false,
			type: 'int'
		},
		{
			mapping: 'sim_param_counter',
			name: 'simulationParameters',
			persist: false,
			type: 'int'
		}
	]
});