/*
 * File: app/view/ActmodPropertiesForm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.view.ActmodPropertiesForm', {
	extend: 'Ext.form.Panel',

	margin: '10px 0',
	width: 687,
	autoScroll: true,
	layout: {
		type: 'auto'
	},
	bodyPadding: '10px',
	titleCollapse: true,

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [
				{
					xtype: 'container',
					layout: {
						align: 'middle',
						pack: 'center',
						type: 'hbox'
					},
					items: [
						{
							xtype: 'fieldset',
							height: 250,
							itemId: 'actmodFieldset',
							width: 305,
							title: 'Properties',
							items: [
								{
									xtype: 'textfield',
									width: 246,
									fieldLabel: 'Name',
									name: 'name',
									listeners: {
										change: {
											fn: me.onTextfieldChange11,
											scope: me
										}
									}
								},
								{
									xtype: 'textfield',
									width: 246,
									fieldLabel: 'Type',
									name: 'type'
								},
								{
									xtype: 'textareafield',
									width: 246,
									fieldLabel: 'Description',
									name: 'description'
								},
								{
									xtype: 'textfield',
									width: 246,
									fieldLabel: 'Day type',
									name: 'day_type',
									listeners: {
										beforerender: {
											fn: me.onTextfieldBeforeRender,
											scope: me
										}
									}
								},
								{
									xtype: 'checkboxfield',
									formBind: false,
									fieldLabel: 'Shiftable',
									name: 'shiftable',
									boxLabel: '',
									checked: true,
									inputValue: 'true',
									uncheckedValue: 'false'
								},
								{
									xtype: 'radiogroup',
									width: 300,
									fieldLabel: 'Configuration',
									labelWidth: 95,
									items: [
										{
											xtype: 'radiofield',
											name: 'config',
											boxLabel: 'Exclusive',
											checked: true,
											inputValue: 'exclusive'
										},
										{
											xtype: 'radiofield',
											name: 'config',
											boxLabel: 'Concurrent',
											inputValue: 'concurrent'
										}
									]
								}
							]
						},
						{
							xtype: 'fieldset',
							margins: '0 10px',
							height: 250,
							itemId: 'appliancesFieldset',
							width: 300,
							autoScroll: true,
							layout: {
								type: 'auto'
							},
							title: 'Appliances',
							items: [
								{
									xtype: 'label',
									style: 'font-size:11px; font-style:italic;',
									text: '*Appliances can be added by droping them from the main tree on the following appliances grid:'
								}
							]
						}
					]
				},
				{
					xtype: 'button',
					itemId: 'btn',
					margin: '10px 0 0 290px',
					width: 70,
					text: 'Update',
					listeners: {
						click: {
							fn: me.onButtonClick2,
							scope: me
						}
					}
				}
			]
		});

		me.callParent(arguments);
	},

	onTextfieldChange11: function(field, newValue, oldValue, eOpts) {
		if(this.getBubbleParent())
		this.getBubbleParent().getBubbleParent().setTitle(newValue);
		var node = C.app.getNodeFromTree(this.form.getRecord().internalId);
		node.set({'name':newValue});
	},

	onTextfieldBeforeRender: function(component, eOpts) {
		component.helpText = 'The following would be valid input examples: </br>- "any" </br>- "weekdays" </br>- "weekends" </br>- specific days: i.e. "[Mon, Tue, Thu]" </br>- specific dates: i.e. "{31/03, 04/05}"';
		component.url = 'https://github.com/cassandra-project/platform/wiki/Activity-Model-form';
	},

	onButtonClick2: function(button, e, eOpts) {
		var gridIds = [];
		var myForm = this.getForm();
		var node = C.app.getNodeFromTree(myForm.getRecord().internalId);
		var record = C.app.getRecordByNode(node);
		var values = myForm.getValues();

		var gridStore = this.query('grid')[0].store;
		var gridData = gridStore.data;

		Ext.each(gridData.items, function(index){
			gridIds.push(index.get('_id'));

		});

		//reload appliances store on activity model store failure to update
		record.store.proxy.on('exception', function(server, response,operation){
			Ext.Ajax.request({
				url: '/cassandra/api/app?actmod_id=' + record.data._id,
				method: 'GET',
				scope: this,
				success: function(response, opts) {
					var o = Ext.decode(response.responseText);
					gridStore.loadData(o.data);
				}
			});
		}, null, { single : true });

			record.set({
				'name':values.name,
				'type': values.type,
				'description': values.description,
				'day_type': values.day_type,
				'shiftable': values.shiftable, 
				'containsAppliances': gridIds,
				'config': values.config
			});

			this.dirtyForm = false;
			//clear dirty record
			record.node.commit();

			if (record.isNew)
			record.isNew = false;
			//record.save();
	}

});