/*
 * File: app/view/ConsumptionModelsForm.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.view.ConsumptionModelsForm', {
	extend: 'Ext.form.Panel',

	height: 388,
	width: 555,
	layout: {
		align: 'center',
		pack: 'center',
		type: 'vbox'
	},
	bodyPadding: 10,
	closable: true,
	title: 'My Form',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [
				{
					xtype: 'container',
					height: 159,
					width: 533,
					activeItem: 0,
					layout: {
						align: 'middle',
						pack: 'center',
						type: 'hbox'
					},
					items: [
						{
							xtype: 'container',
							padding: '10px',
							flex: 1,
							items: [
								{
									xtype: 'textfield',
									width: 246,
									name: 'name',
									fieldLabel: 'Name'
								},
								{
									xtype: 'textfield',
									width: 246,
									name: 'type',
									fieldLabel: 'Type'
								},
								{
									xtype: 'textareafield',
									width: 246,
									name: 'description',
									fieldLabel: 'Description'
								}
							]
						},
						{
							xtype: 'container',
							padding: '10px',
							width: 266,
							flex: 0,
							items: [
								{
									xtype: 'numberfield',
									width: 246,
									name: 'model_n',
									fieldLabel: 'No of iterations n',
									allowDecimals: false
								},
								{
									xtype: 'numberfield',
									width: 246,
									name: 'params_n',
									fieldLabel: 'No of iterations n (params)',
									allowDecimals: false
								}
							]
						}
					]
				},
				{
					xtype: 'button',
					margin: '10px 0 0 120px',
					text: 'Update',
					flex: 1,
					listeners: {
						click: {
							fn: me.onButtonClick2,
							scope: me
						}
					}
				}
			]
		});

		me.callParent(arguments);
	},

	onButtonClick2: function(button, e, options) {
		var model = [];
		var properties = [];
		var params = [];
		var myForm = this.getForm();
		var record = myForm.getRecord(),
		values = myForm.getFieldValues();
		console.info(record, this.query('grid')[0].store.data);
		var gridData = this.query('grid')[0].store.data;

		Ext.each(gridData.items, function(index){
			properties.push(index.data);

		});

		params[0] = { n: values.params_n, values: properties};
		model = { n: values.model_n, params: params};

		console.info(model,'model');
		record.set('model', model);

		myForm.updateRecord();
		//record.save();
	}

});