/*
 * File: app/view/ConsModChart.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.view.ConsModChart', {
	extend: 'Ext.chart.Chart',

	height: 397,
	style: 'background:#fff',
	width: 900,
	shadow: true,
	animate: true,
	insetPadding: 20,
	store: 'ConsumptionModelValues',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			axes: [
				{
					type: 'Numeric',
					fields: [
						'x'
					],
					minorTickSteps: 10,
					position: 'bottom',
					title: 'Time'
				},
				{
					type: 'Numeric',
					fields: [
						'y'
					],
					grid: {
						odd: {
							opacity: 1,
							fill: '#ddd',
							stroke: '#bbb',
							'stroke-width': 0.5
						}
					},
					position: 'left',
					title: 'Watt',
					adjustMaximumByMajorUnit: true,
					minimum: 0
				}
			],
			series: [
				{
					type: 'column',
					highlight: true,
					label: {
						contrast: true,
						display: 'insideEnd',
						field: 'y',
						color: '#000',
						orientation: 'vertical',
						'text-anchor': 'middle'
					},
					tips: {
						trackMouse: true,
						width: 100,
						height: 40,
						renderer: function(storeItem, item) {
							this.setTitle( 'Watt : ' + storeItem.get('y') + '<br />' + 'Time : ' + storeItem.get('x'));
						}
					},
					xField: 'x',
					yField: [
						'y'
					]
				}
			],
			legend: {

			},
			listeners: {
				afterrender: {
					fn: me.onChartAfterRender,
					scope: me
				}
			}
		});

		me.callParent(arguments);
	},

	onChartAfterRender: function(abstractcomponent, options) {
		console.info('on after render', abstractcomponent, options);

		abstractcomponent.store.on(
		'load',	
		function(store){
			if (store.data.length > 150)
			abstractcomponent.series.items[0].label = {};
		});
	}

});