/*
 * File: app/view/DemographicForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.view.DemographicForm', {
	extend: 'Ext.form.Panel',

	margin: '10px 0',
	padding: '',
	autoScroll: true,
	layout: {
		type: 'auto'
	},
	bodyPadding: '10px',
	closable: true,

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [
				{
					xtype: 'container',
					width: 620,
					layout: {
						type: 'hbox'
					},
					items: [
						{
							xtype: 'container',
							flex: 1,
							items: [
								{
									xtype: 'fieldset',
									height: 220,
									itemId: 'demogFieldset',
									width: 300,
									title: 'Properties',
									items: [
										{
											xtype: 'textfield',
											width: 246,
											name: 'name',
											fieldLabel: 'Name',
											listeners: {
												change: {
													fn: me.onTextfieldChange11,
													scope: me
												}
											}
										},
										{
											xtype: 'textfield',
											width: 246,
											name: 'type',
											fieldLabel: 'Type'
										},
										{
											xtype: 'textareafield',
											width: 246,
											name: 'description',
											fieldLabel: 'Description'
										},
										{
											xtype: 'textfield',
											width: 246,
											name: 'numberOfEntities',
											readOnly: true,
											fieldLabel: 'Number of entities'
										}
									]
								},
								{
									xtype: 'button',
									margin: '10px 120px',
									width: 70,
									autoWidth: false,
									text: 'Update',
									listeners: {
										click: {
											fn: me.onButtonClick2,
											scope: me
										}
									}
								}
							]
						},
						{
							xtype: 'fieldset',
							margins: '0 10px',
							itemId: 'entitiesFieldset',
							minHeight: 220,
							width: 300,
							autoScroll: true,
							layout: {
								type: 'auto'
							},
							title: 'Entities',
							items: [
								{
									xtype: 'label',
									style: 'font-size:11px; font-style:italic;',
									text: '*Entities can be added by droping  persons or appliances under the collection node to the following entities grid:'
								}
							]
						}
					]
				}
			]
		});

		me.callParent(arguments);
	},

	onTextfieldChange11: function(field, newValue, oldValue, options) {
		this.setTitle(newValue);
	},

	onButtonClick2: function(button, e, options) {
		var gridGenerators = [];
		var myForm = this.getForm();
		var record = myForm.getRecord(),
		values = myForm.getFieldValues();

		var gridData = this.query('grid')[0].store.data;

		Ext.each(gridData.items, function(item, index){
			gridGenerators.push(item.data);
		});

		record.set('generators', gridGenerators);

		myForm.updateRecord();console.info(record);
		//record.save();

		//TODO: only one request to server
	}

});