/*
 * File: app/view/FileUploadForm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.view.FileUploadForm', {
	extend: 'Ext.form.Panel',

	height: 100,
	width: 300,
	bodyPadding: 10,

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			defaults: {
				allowBlank: false,
				msgTarget: 'under'
			},
			items: [
				{
					xtype: 'filefield',
					anchor: '100%',
					fieldLabel: 'File',
					labelWidth: 30,
					name: 'file'
				},
				{
					xtype: 'button',
					handler: function(button, event) {
						var form = this.up('form').getForm();
						if(form.isValid()){
							form.submit({
								url: '/cassandra/api/file/upload',
								waitMsg: 'Uploading your file...',
								success: function(fp, o) {
									Ext.sliding_box.msg('Success',  'Processed file "' + o.result.file + '" on the server');
								},
								failure: function(fp, o) {
									Ext.MessageBox.show({title:'Error', msg: "File upload failed.</br> Please try uploading your file again.", icon: Ext.MessageBox.ERROR, buttons: Ext.MessageBox.OK}); 
								}
							});
						}
					},
					margin: '10 0 0 100',
					text: 'Upload'
				}
			]
		});

		me.callParent(arguments);
	}

});