/*
 * File: app/view/SimulationParamsForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.view.SimulationParamsForm', {
	extend: 'Ext.form.Panel',

	height: 296,
	width: 315,
	layout: {
		type: 'auto'
	},
	bodyPadding: 10,
	closable: true,
	title: 'My Form',

	initComponent: function() {
		var me = this;

		Ext.applyIf(me, {
			items: [
				{
					xtype: 'container',
					autoScroll: true,
					layout: {
						type: 'anchor'
					},
					items: [
						{
							xtype: 'fieldset',
							padding: '10px',
							title: 'Properties',
							items: [
								{
									xtype: 'textfield',
									width: 246,
									name: 'name',
									fieldLabel: 'Name'
								},
								{
									xtype: 'textareafield',
									width: 246,
									name: 'description',
									fieldLabel: 'Description'
								},
								{
									xtype: 'textfield',
									width: 246,
									name: 'locationInfo',
									fieldLabel: 'Location'
								},
								{
									xtype: 'numberfield',
									width: 246,
									name: 'numberOfDays',
									readOnly: false,
									fieldLabel: 'Duration',
									allowDecimals: false
								},
								{
									xtype: 'datefield',
									width: 246,
									name: 'formCalendar',
									readOnly: false,
									fieldLabel: 'Calendar'
								},
								{
									xtype: 'button',
									margin: '10px 0 0 185px',
									width: 70,
									autoWidth: false,
									text: 'Update',
									listeners: {
										click: {
											fn: me.onButtonClick2,
											scope: me
										}
									}
								}
							]
						}
					]
				}
			]
		});

		me.callParent(arguments);
	},

	onButtonClick2: function(button, e, options) {
		var myForm = this.getForm();
		var record = myForm.getRecord(),
		values = myForm.getFieldValues();


		myForm.updateRecord();console.info(record);

		var date = myForm.getFieldValues().formCalendar;
		if (date) {
			var day = date.getDate();
			var month = date.getMonth()+1;
			var year = date.getFullYear();
			var weekdayNumb = date.getDay( );
			var weekday = '';
			switch (weekdayNumb) {
				case 0: weekday = 'Sunday';break;
				case 1: weekday = 'Monday';break;
				case 2: weekday = 'Tuesday';break;
				case 3: weekday = 'Wednesday';break;
				case 4: weekday = 'Thursday';break;
				case 5: weekday = 'Friday';break;
				case 6: weekday = 'Saturday';break;
			}
			calendar = {'year':year, 'month': month, 'weekday': weekday, 'dayOfMonth':day};
		}
		else
		calendar = {};
		record.set('calendar', calendar);
		//record.save();
	}

});