/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.view.Viewport', {
	extend: 'C.view.MyViewport',
	renderTo: Ext.getBody(),
	requires: [
		'C.view.ActivitiesGrid',
		'C.view.ActmodPropertiesForm',
		'C.view.ActivityModelForm',
		'C.view.ScenarioForm',
		'C.view.PersonForm',
		'C.view.ActivityForm',
		'C.view.SimulationParamsForm',
		'C.view.InstallationForm',
		'C.view.ApplianceForm',
		'C.view.ActivityModelsGrid',
		'C.view.AppliancesGrid',
		'C.view.ConsumptionModelsGrid',
		'C.view.RelationsGrid',
		'C.view.DistributionInActivityGrid',
		'C.view.DistributionForm',
		'C.view.DistributionsGrid',
		'C.view.DynamicGrid',
		'C.view.InstallationsGrid',
		'C.view.MyViewport',
		'C.view.PersonsGrid',
		'C.view.RunsGrid',
		'C.view.ScenariosGrid',
		'C.view.SimulationParamsGrid',
		'C.view.TypesPieChart'
	]
});