/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('C.view.Viewport', {
	extend: 'C.view.MyViewport',
	renderTo: Ext.getBody(),
	requires: [
		'C.view.MyViewport',
		'C.view.ScenariosGrid',
		'C.view.RunsGrid',
		'C.view.InstallationsGrid',
		'C.view.PersonsGrid',
		'C.view.ActivitiesGrid',
		'C.view.DistributionsGrid',
		'C.view.DistributionParamsGrid',
		'C.view.ConsumptionModelParamsGrid',
		'C.view.ConsumptionModelsGrid',
		'C.view.SimulationParamsGrid',
		'C.view.AppliancesGrid',
		'C.view.ActivityModelsGrid',
		'C.view.ContainsAppliancesGrid',
		'C.view.DistributionInActivityGrid',
		'C.view.ActivityModelsForm',
		'C.view.DistributionsForm',
		'C.view.ConsumptionModelsForm'
	]
});